version: "3.8"

services:
  webizly:
    image: kaw393939/mywebsite:master 
    container_name: njitesports 
    pull_policy: always
    restart: always
    networks:
       - traefik
       - backend
    ports:
      - "80"
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.njitesports.rule=Host(`njitesports.me`) || Host(`njitesports.me`)
      - traefik.http.routers.njitesports.entrypoints=https
      - traefik.http.routers.njitesports.tls=true
      - traefik.http.routers.njitesports.tls.certresolver=simple-resolver
      - traefik.http.services.njitesports.loadbalancer.server.port=80
networks:
  traefik:
      name: traefik
      external: true
  backend:
      external: true
