version: "3.8"

services:
  pgadmin:
    image: dpage/pgadmin4:8.13.0
    container_name: pgadmin 
    pull_policy: always
    restart: always
    environment: 
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin  
    networks:
       - traefik
       - backend
    ports:
      - "80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.pgamin.rule=Host(`pgadmin.njitesports.me`)
      - traefik.http.routers.pgadmin.entrypoints=https
      - traefik.http.routers.pgadmin.tls=true
      - traefik.http.routers.pgadmin.tls.certresolver=simple-resolver
      - traefik.http.services.pgadmin.loadbalancer.server.port=80


volumes:
  pgadmin_data:
    driver: local


networks:
  traefik:
      name: traefik
      external: true
  backend:
      external: true
